export const REGIONS_GET = 'REGIONS_GET'
export const REGIONS_GET_SUCCESSFULL = 'REGIONS_GET_SUCCESSFULL'

export const MAIN_GENERATIONS_GET = 'MAIN_GENERATIONS_GET'
export const MAIN_GENERATIONS_GET_SUCCESSFULL =
  'MAIN_GENERATIONS_GET_SUCCESSFULL'

export const POKEMONS_BY_REGION_GET = 'POKEMONS_BY_REGION_GET'
export const POKEMONS_BY_REGION_GET_SUCCESSFULL =
  'POKEMONS_BY_REGION_GET_SUCCESSFULL'

export const RESET_STATE = 'RESET_STATE'
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL'
export const GET_POKEMON_DETAIL_SUCCESS = 'GET_POKEMON_DETAIL_SUCCESS'
